apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts
  labels:
    name: accounts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: accounts
    spec:
      containers:
      - name: accounts
        image: weaveworksdemos/accounts:snapshot
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    name: accounts
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: accounts
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts-db
  labels:
    name: accounts-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: accounts-db
    spec:
      containers:
      - name: accounts-db
        image: weaveworksdemos/accounts-db-test:snapshot

        ports:
        - name: mongo
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
  labels:
    name: accounts-db
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: accounts-db
